In [87]:
import numpy as np
1.[簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？
為什麼要設計兩種方法？
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

SyntaxError: invalid syntax (<ipython-input-87-ac8dcb82641c>, line 2)

In [148]:
'answer(1)' 
'zeros全零矩陣，empty產出很小很小的數,empty可用於初始化，但之後數值可能會重寫的情況'

'zeros全零矩陣，empty產出很小很小的數,empty可用於初始化，但之後數值可能會重寫的情況'

In [88]:
2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？
請將給定的 a 陣列當中的元素變成去掉小數變成整數

SyntaxError: invalid character in identifier (<ipython-input-88-2096b20f7dd0>, line 1)

In [149]:
'answer(2)'


'answer(2)'

In [150]:
from numpy.random import default_rng
rng=default_rng()
a=rng.random((2,3))
a=a*100
print(a)
print(a.round())
print(np.round(a))

[[66.58993686 75.66382549 19.64622533]
 [96.68238575 77.4983733  63.42569504]]
[[67. 76. 20.]
 [97. 77. 63.]]
[[67. 76. 20.]
 [97. 77. 63.]]


In [154]:
'3. 承上題,怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。'

'3. 承上題,怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。'

In [155]:
'answer 3'

'answer 3'

In [186]:
m=20
n=40
a=rng.random((2,3))*(n-m)
b=a

print((a-b%1)+m)

[[35. 38. 34.]
 [33. 35. 24.]]
