In [7]:
'1.請問下列程式碼，運算結果分別為何？'


'1.請問下列程式碼，運算結果分別為何？'

In [27]:
'answer 1'
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] )
print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)
'1x4矩陣無法直接相加1x2矩陣,邏輯有誤'

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [28]:
'2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？'

'2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？'

In [123]:
'answer 2'
A = np.ones(3)*1
B = np.ones(3)*2

print((A+B)*(-A/2))

[-1.5 -1.5 -1.5]


In [154]:
A=[1,1,1]
B=[2,2,2]
C=[]
for i,j in zip(A,B):
    C.append((i+j)*(-i/2))
    print(C)

[-1.5]
[-1.5, -1.5]
[-1.5, -1.5, -1.5]


In [155]:
'3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？'


'3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？'

In [157]:
'answer 3'
A = np.ones((1,6))
B = np.ones((6,1))
print(np.dot(A,B))
print(np.outer(A,B))

[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
