In [1]:
import numpy as np

In [20]:
'1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。'

'1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。'

In [82]:
'answer 1'
a=np.arange(1,12)
a[(a<=6)&(a>=3)] *=-1
print(a)
    

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [83]:
'2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？'


'2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？'

In [107]:
'answer 2'
A = np.random.rand(3, 6)
biggerthenpointfive=A[A>0.5]
print(A)
print(A>0.5)
print(biggerthenpointfive.size)

[[0.68119803 0.13124218 0.75903083 0.50597583 0.85759157 0.11152833]
 [0.46786716 0.86289318 0.63826937 0.33372682 0.7292934  0.50927439]
 [0.37157489 0.53178184 0.56474931 0.94758573 0.76474225 0.72832956]]
[[ True False  True  True  True False]
 [False  True  True False  True  True]
 [False  True  True  True  True  True]]
13
