In [33]:
#1.[簡答題] 請問下列這三種方法有什麼不同？
import numpy as np 

a = np.arange(6).reshape((3, 2))


print(a.sum()) #回傳所有庶子加總的值
print(np.sum(a))#回傳所有數字加總的值
print(sum(a))#回傳axis=0加總起來的值

15
15
[6 9]


In [46]:
#2. 請對一個 5x5 的隨機矩陣作正規化的操作。
A=np.random.random((5,5))
print(A)
Amin,Amax=A.min(),A.max()
a=(A-Amin)/(Amax-Amin)
print('__________正規化之後______________')
print(a)

[[0.67366352 0.07560698 0.53908104 0.06188524 0.07463338]
 [0.93337241 0.82912425 0.68192539 0.98586504 0.35986868]
 [0.912055   0.4794271  0.19288465 0.88266068 0.38060777]
 [0.4198225  0.03892444 0.70178717 0.16725986 0.65630919]
 [0.74203049 0.27213471 0.91163963 0.44312553 0.39042471]]
__________正規化之後______________
[[0.67030507 0.03873796 0.5281816  0.02424735 0.03770981]
 [0.94456608 0.83447664 0.67902986 1.         0.33892753]
 [0.9220542  0.4651851  0.16258698 0.89101285 0.36082869]
 [0.40224071 0.         0.70000455 0.13552637 0.65197833]
 [0.7425028  0.24627761 0.92161555 0.42684946 0.37119569]]


In [72]:
#3.請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
z=np.random.randint(0,100,10)
print(z)
print('最大值-> -1')
z[z.argmax()]=-1
print(z)

[81 44 59 72 69 26 10 82  3 79]
最大值-> -1
[81 44 59 72 69 26 10 -1  3 79]
