In [2]:
import numpy as np
#1.
a = np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#2.
print(a[::2])

[ 0  2  4  6  8 10 12 14 16 18 20]


In [4]:
#3.
print(a[::3])

[ 0  3  6  9 12 15 18]


In [6]:
#4. 
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
#list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉； tolist() 才能達成多層的型態轉換。

list(a):  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
tolist():  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [22]:
#5.1
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))    

[6 4 2 9 6 0]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [23]:
#5.2
b = np.random.randint(10, size=(3,4))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[4 2 6 9]
 [7 8 8 4]
 [1 8 5 3]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [24]:
#5.3
c = np.random.randint(10, size=(2,3,2))
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[7 8]
  [4 3]
  [0 5]]

 [[2 4]
  [8 8]
  [3 0]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [25]:
#6.
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

tolist_ = lambda arr: list(map(tolist_, arr)) if isinstance(arr, np.ndarray) else arr

for i in [a,b,c]:
    print(list(tolist_(i)))
    print(i.tolist())

[2, 5, 6, 3, 0, 5]
[2, 5, 6, 3, 0, 5]
[[9, 7, 8, 1], [7, 3, 4, 7], [1, 2, 8, 6]]
[[9, 7, 8, 1], [7, 3, 4, 7], [1, 2, 8, 6]]
[[[2, 3], [5, 1], [7, 0]], [[0, 3], [7, 2], [3, 9]]]
[[[2, 3], [5, 1], [7, 0]], [[0, 3], [7, 2], [3, 9]]]
